CREATE TABLE treinador_entity
(
    id   INT NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_treinadorentity PRIMARY KEY (id)
);
CREATE TABLE treinador_entity
(
    id   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_treinadorentity PRIMARY KEY (id)
);

CREATE TABLE treinador_entity_itens
(
    treinador_entity_id INT NOT NULL,
    itens_id            INT NOT NULL
);

CREATE TABLE treinador_entity_pokemons
(
    treinador_entity_id INT NOT NULL,
    pokemons_id         INT NOT NULL
);

ALTER TABLE treinador_entity_itens
    ADD CONSTRAINT uc_treinador_entity_itens_itens UNIQUE (itens_id);

ALTER TABLE treinador_entity_pokemons
    ADD CONSTRAINT uc_treinador_entity_pokemons_pokemons UNIQUE (pokemons_id);

ALTER TABLE treinador_entity_itens
    ADD CONSTRAINT fk_treentite_on_itens_object FOREIGN KEY (itens_id) REFERENCES itens_object (id);

ALTER TABLE treinador_entity_itens
    ADD CONSTRAINT fk_treentite_on_treinador_entity FOREIGN KEY (treinador_entity_id) REFERENCES treinador_entity (id);

ALTER TABLE treinador_entity_pokemons
    ADD CONSTRAINT fk_treentpok_on_pokemon_entity FOREIGN KEY (pokemons_id) REFERENCES pokemon_entity (id);

ALTER TABLE treinador_entity_pokemons
    ADD CONSTRAINT fk_treentpok_on_treinador_entity FOREIGN KEY (treinador_entity_id) REFERENCES treinador_entity (id);