CREATE TABLE arena_entity
(
    id    INT NOT NULL,
    name  VARCHAR(255),
    type  SMALLINT,
    lider SMALLINT,
    CONSTRAINT pk_arenaentity PRIMARY KEY (id)
);
CREATE TABLE arena_entity
(
    id    INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255),
    type  SMALLINT,
    lider SMALLINT,
    CONSTRAINT pk_arenaentity PRIMARY KEY (id)
);

CREATE TABLE arena_entity_pokemons
(
    arena_entity_id INT NOT NULL,
    pokemons_id     INT NOT NULL
);

ALTER TABLE arena_entity_pokemons
    ADD CONSTRAINT uc_arena_entity_pokemons_pokemons UNIQUE (pokemons_id);

ALTER TABLE arena_entity_pokemons
    ADD CONSTRAINT fk_areentpok_on_arena_entity FOREIGN KEY (arena_entity_id) REFERENCES arena_entity (id);

ALTER TABLE arena_entity_pokemons
    ADD CONSTRAINT fk_areentpok_on_pokemon_entity FOREIGN KEY (pokemons_id) REFERENCES pokemon_entity (id);